# Generated by Django 4.2.5 on 2023-12-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id_pharmacie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pharmacie', models.CharField(max_length=100)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_medicament', models.AutoField(primary_key=True, serialize=False)),
                ('nom_medicament', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=0)),
                ('date_expiration', models.DateField()),
                ('nom_pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedecineApp.pharmacie')),
            ],
        ),
    ]
